version: '3'
services:
  mongodb:
    environment:
      - DOCKER_DEFAULT_PLATFORM=linux/amd64
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./mongo/create_indexes.js:/docker-entrypoint-initdb.d/create_indexes.js
    ports:
      - 27017:27017

  mongo_seed:
    environment:
        - DOCKER_DEFAULT_PLATFORM=linux/amd64
    image: mongo:latest
    depends_on:
      - mongodb
    links:
      - mongodb
    volumes:
      - ./mongo:/mongo
    command:
      - /mongo/import.sh
