version: '3'
services:
  mongodb:
    image: mongo:3.4.0
    container_name: mongodb
    ports:
      - 27017:27017

  mongo_seed:
    image: mongo:3.4.0
    depends_on:
      - mongodb
    links:
      - mongodb
    volumes:
      - ./mongo:/mongo
    command:
      /mongo/import.sh
